language: php

php:
  - 7.0
  - hhvm

matrix:
  fast_finish: true

before_install:
  - composer self-update

install:
  - travis_retry composer install --prefer-source

before_script:
 - mkdir -p tests/files

script:
  - ./vendor/bin/phpunit;
