language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

before_install:
  - composer self-update

install:
  - travis_retry composer install --prefer-source

before_script:
 - mkdir -p tests/files

script:
  - ./vendor/bin/phpunit;
